name: raktsanchar
description: Raktsanchar Rider App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # 🔐 Supabase (REQUIRED AT RUNTIME)
  supabase_flutter: ^2.5.6

  # 🗺️ OpenStreetMap
  flutter_map: ^6.1.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/map.png
    - assets/logo.png
    - assets/india_flag.png
    - assets/rider.png